### ISSUE TITLE
工程跑不起来啊

### ISSUE THREAD

**Issue by acaixuediananao** [yohnz/maoyanFilm#3]
react-native 报错，执行react-native run-android命令后，PS：npm install 和react-native start命令已经执行，报错如下
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

我是连了手机的，而且执行我自己创建的项目的时候是没问题的

**Comment by yohnz** [comment]
@acaixuediananao 换其它手机或者模拟器试试

**Comment by drduan** [comment]
我导入android studio可以运行 但是我用那个命令却不行

**Comment by acaixuediananao** [comment]
@yohnz 换其他手机也不行，但是我通过android studio启动工程的话，就是可以启动的@drduan,说的没错，我也是android studio可以运行，但是执行命令运行的话，就不起来

**Comment by jeffhtli** [comment]
应该是apk安装失败了，有的手机installDebug会失败。不过编译已经成功了，可以手动安装：

adb install ./android/app/build/outputs/apk/app-debug.apk
