### ISSUE TITLE
Index类在哪里？

### ISSUE THREAD

**Issue by daojj** [yohnz/maoyanFilm#4]
import Index from "./main"; 在main.js里没有看到Index?

在index.android.js和main.js里都定义了film类，实际用的是哪个？

**Comment by yohnz** [comment]
@daojj 
Index只是一个 变量名，可以随意取，我把index.android.js和index.ios.js都统一如下了，这样比较清晰：

```
import film from "./main"
AppRegistry.registerComponent('film', () => film);
```
