### ISSUE TITLE
Where is TabBarItem?

### ISSUE THREAD

**Issue by daojj** [yohnz/maoyanFilm#5]
In main.js:

import TabBarItem from "./utils/TabBarItem";

But in utils/TabBarItem.js, no TabBarItem class, where is the TabBarItem Component?

**Comment by yohnz** [comment]
@daojj TabBarItem exports a default funciton。You can import it by any variable and don't have to know the name of the Class。
[This is the detail](http://es6.ruanyifeng.com/#docs/module#export-default命令)
